import type {
  JsonValue,
  SeedDataset,
  SeedRow,
  SeedTable,
  SqlExpression,
} from "./seed-data.js";

export function buildSeedSql(dataset: SeedDataset): string {
  const statements = dataset.tables.flatMap((table) =>
    buildTableStatements(table),
  );
  return [
    "-- Generated by supabase/seed/run-seed.ts. Do not edit generated output by hand.",
    "begin;",
    "set local search_path = app, public, extensions, pg_catalog;",
    ...statements,
    "commit;",
    "",
  ].join("\n\n");
}

function buildTableStatements(table: SeedTable): string[] {
  if (table.rows.length === 0) {
    return [];
  }

  const chunkSize = 200;
  const chunks: SeedRow[][] = [];
  for (let index = 0; index < table.rows.length; index += chunkSize) {
    chunks.push([...table.rows.slice(index, index + chunkSize)]);
  }

  return chunks.map((chunk) => buildUpsert(table, chunk));
}

function buildUpsert(table: SeedTable, rows: readonly SeedRow[]): string {
  const columnList = table.columns
    .map((column) => quoteIdentifier(column))
    .join(", ");
  const values = rows
    .map(
      (row) =>
        `  (${table.columns.map((column) => toSql(row[column] ?? null)).join(", ")})`,
    )
    .join(",\n");
  const conflict = table.conflictColumns
    .map((column) => quoteIdentifier(column))
    .join(", ");
  const updateColumns = table.columns.filter(
    (column) => !table.conflictColumns.includes(column),
  );
  const updates = updateColumns
    .map(
      (column) =>
        `${quoteIdentifier(column)} = excluded.${quoteIdentifier(column)}`,
    )
    .join(", ");

  return `insert into ${table.name} (${columnList})\nvalues\n${values}\non conflict (${conflict}) do update set\n  ${updates};`;
}

function toSql(value: SeedRow[string]): string {
  if (isSqlExpression(value)) {
    return value.sql;
  }
  if (value === null) {
    return "null";
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "number") {
    return Number.isInteger(value) ? String(value) : value.toFixed(6);
  }
  if (typeof value === "string") {
    return quoteLiteral(value);
  }
  return `${quoteLiteral(JSON.stringify(value satisfies JsonValue))}::jsonb`;
}

function isSqlExpression(value: unknown): value is SqlExpression {
  return (
    typeof value === "object" &&
    value !== null &&
    "sql" in value &&
    typeof value.sql === "string"
  );
}

function quoteIdentifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}
