import { useEffect, useRef, useState, type ReactNode } from "react";
import type { ReactivationEntry, ReactivationReview, ReactivationOutcome } from "../../../../shared/src/reactivation.js";
import { demoApi, ApiRequestError } from "../../lib/api.js";
import { FraudNetPreparation } from "../checkout/paypal-wallet-button.js";
const money=(cents:number)=>`$${(cents/100).toFixed(2)}`;
type ViewProps={entry:ReactivationEntry;review:ReactivationReview|null;outcome:ReactivationOutcome|null;busy:boolean;ready:boolean;error:string|null;onReview():void;onConfirm():void;preparation?:ReactNode};
export function ReactivationView(p:ViewProps) {
 const state=p.busy?(p.review?"submitting":"loading"):p.outcome?.state??(p.review?"review":"expired");
 const copy={expired:["Service period ended","Expired included allowance is not available. Nothing is charged when you open this page."],loading:["Loading your review","No payment has been submitted."],review:["Review before paying","Confirm this one recovery payment using your existing saved wallet. No overdue period is charged."],submitting:["Submitting recovery payment","Payment controls are disabled while the result is confirmed."],pending:["Payment confirmation pending","No new allowance has been granted. Do not pay again while this payment is being checked."],action_required:["Payment review needed","No new term or allowance has been granted. This payment needs separately authorized review."],failed:["Payment was not completed","No new term or allowance was granted. No retry is submitted here."],confirmed:["New period verified","One full calendar month and 100 included units have been granted."]}[state];
 return <main className="reactivation-main" data-state={state}>
  <section className="reading-surface reactivation-panel" aria-labelledby="reactivation-heading"><p className="eyebrow">Your existing subscription</p><h1 id="reactivation-heading">Welcome back.<br/>Restore your Go.</h1><p className="section-copy">Your paid period has ended. Your account, payment history and saved wallet are retained.</p><div className="reactivation-note" role="status" aria-live="polite"><strong>{copy[0]}</strong><p>{copy[1]}</p></div><p>Previous period and payment remain in your history. Recovery does not collect a missed-period charge.</p>
  {state==="expired"?<button className="primary-button" disabled={!p.entry.canReview} onClick={p.onReview}>Review recovery payment</button>:null}
  {state==="expired"&&!p.entry.canReview?<p>{p.entry.blocker==="payment_pending"?"An earlier payment is still being checked. Do not pay again.":"The original saved wallet is not available for payment."}</p>:null}
  {p.outcome?.term?<p>Verified period: <time dateTime={p.outcome.term.startsAt}>{p.outcome.term.startsAt}</time> to <time dateTime={p.outcome.term.endsAt}>{p.outcome.term.endsAt}</time> · {p.outcome.term.timeZone}</p>:null}
  {p.error?<p role="alert" className="error-note">{p.error}</p>:null}
  </section>
  <section className="reading-surface reactivation-panel" aria-labelledby="recovery-review-title"><p className="eyebrow">Fresh monthly term</p><h2 id="recovery-review-title">Go Monthly</h2>
  {p.review?<><dl className="reactivation-price"><div><dt>Normal monthly price</dt><dd>{money(p.review.base.cents)}</dd></div><div><dt>Introductory discount</dt><dd>Not applicable</dd></div><div><dt>Tax</dt><dd>{money(p.review.tax.cents)}</dd></div><div className="reactivation-total"><dt>Due for recovery</dt><dd>{money(p.review.dueToday.cents)}</dd></div></dl><p className="muted">{p.review.taxVersion}<br/>Review expires <time dateTime={p.review.expiresAt}>{p.review.expiresAt}</time></p></>:<p>The server-issued review will show the normal monthly price, effective tax and expiry before you confirm.</p>}
  <div className="reactivation-note"><strong>Saved PayPal wallet</strong><p>The server verifies ownership and eligibility before payment. No new wallet will be saved.</p></div><p>A full calendar-month period and 100 included units begin only after verified payment. Expired allowance is not carried forward.</p><p>Automatic renewal is not enabled by this recovery. Wallet removal is a separate action.</p>
  {p.preparation}
  {state==="review"&&p.review?<button className="primary-button" disabled={!p.ready||p.busy||Boolean(p.error)} onClick={p.onConfirm}>Confirm {money(p.review.dueToday.cents)} recovery</button>:null}
  <p className="muted">Merchant confirmation control, not an official PayPal button. Preparation readiness is not verified funding.</p></section>
 </main>;
}
export function ReactivationRecovery({entry,token,onRecovered}:{entry:ReactivationEntry;token:string;onRecovered():void}){
 const storageKey=`go-recovery-${entry.arrangementId}`;const [prior]=useState(()=>sessionStorage.getItem(storageKey));
 const [review,setReview]=useState<ReactivationReview|null>(null);const [outcome,setOutcome]=useState<ReactivationOutcome|null>(null);const [ready,setReady]=useState(false);const [busy,setBusy]=useState(Boolean(prior));const [error,setError]=useState<string|null>(null);const claimed=useRef(Boolean(prior));const [metadata]=useState(()=>crypto.randomUUID().replaceAll("-",""));
 const restored=useRef(onRecovered);useEffect(()=>{restored.current=onRecovered;},[onRecovered]);
 useEffect(()=>{if(!prior)return;let active=true;void demoApi.readReactivationOutcome(prior,token).then(result=>{if(active){setOutcome(result);if(result.state==="confirmed")restored.current();}},()=>{if(active)setError("The previous payment status is unavailable. Do not pay again.");}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[token,prior]);
 async function openReview(){if(busy||claimed.current)return;setBusy(true);setReady(false);setError(null);try{setReview(await demoApi.reviewReactivation({arrangementId:entry.arrangementId,...(review?{currentQuoteId:review.quoteId}:{})},token));}catch{setError("Recovery review is not available. No payment was submitted.");}finally{setBusy(false);}}
 async function confirm(){if(!review||!ready||busy||claimed.current)return;if(Date.parse(review.expiresAt)<=Date.now()){setReady(false);setError("This review expired. A new review and confirmation are required.");return;}claimed.current=true;setBusy(true);setError(null);try{let result=await demoApi.confirmReactivation({arrangementId:entry.arrangementId,quoteId:review.quoteId,confirmed:true,clientMetadataId:metadata},token);sessionStorage.setItem(storageKey,result.operationId);setOutcome(result);if(result.state==="pending"){result=await demoApi.readReactivationOutcome(result.operationId,token);setOutcome(result);}if(result.state==="confirmed")onRecovered();}catch(e){if(e instanceof ApiRequestError&&e.status===409&&e.code==="stale_quote"){claimed.current=false;setReview(null);setReady(false);setError("The quote changed or expired. Review the current amount and confirm again.");}else setError("Payment status could not be confirmed. No new allowance is shown. Do not pay again; refresh to check the retained state.");}finally{setBusy(false);}}
 useEffect(()=>{if(!review)return;const timer=setTimeout(()=>{setReady(false);setReview(null);setError("This review expired. Review the current amount before confirming.");},Math.max(0,Date.parse(review.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[review]);
 return <ReactivationView entry={entry} review={review} outcome={outcome} busy={busy} ready={ready} error={error} onReview={()=>void openReview()} onConfirm={()=>void confirm()} preparation={review&&!outcome&&!busy&&!error?<FraudNetPreparation bootstrap={review.fraudNet} clientMetadataId={metadata} nonce={document.querySelector('meta[name="csp-nonce"]')?.getAttribute('content')??""} onReady={()=>setReady(true)} onFailure={()=>setError("Risk preparation could not load. No payment was submitted.")}/>:null}/>;
}
